### ISSUE TITLE
Multidimensions can trap player in an endless death loop

### ISSUE THREAD

**Issue by orbea** [AiTechEye/multidimensions#1]
minetest: `5.2.0`
multidimensions: https://github.com/AiTechEye/multidimensions/commit/aaf75c49abf8539f35adf208fe9319a9666dff94

I found that the multidimensions mod can easily teleport the player to a new dimension, but in an extremely unsafe location which will always result in death. When they do not have the `dimensions` privilege they will then respawn in the same location just to die again and again... If they do have the `dimensions` privilege they will then be transported back to Earth, but not at the default spawn or the players bed and this could be an equally dangerous location.

One way to reproduce:

1. Make sure the player does not have the `dimensions` privilege.
2. Get a floatlands teleport block and use it.
3. If you are unlucky you spawn over nothing.
4. Fall and die.
5. Repeat step 4.

Another way:

1. Enable the `dimensions` privilege for the player.
2. Teleport to a new dimensions.
3. Wonder some ways and then die.
4. The player will return to earth in a unfamiliar location.
5. If they are unlucky  they will spawn in a dangerous location such as lava and die.

I suggest that each new dimension should have its own spawn that uses similar methods as the default game to ensure its safe. When teleporting back to Earth it should use the default spawn or otherwise maybe the player's bed if available.

Also, how are players supposed to get back to Earth? I don't see way to craft the teleport to Earth block with the crafting guide.

**Comment by AiTechEye** [comment]
yeah, there should be a safer way, and if someone gets teleported by a mistake.
there could be some kind of block/teleport back and at least a platform under it so the player not just falls down.

thanks for your attention

**Comment by orbea** [comment]
Also I found this minetest engine bug when testing the multidimensions floatlands, it may interest you.

https://github.com/minetest/minetest/issues/9738

**Comment by AiTechEye** [comment]
fixed, by placing a platform under the player if its in air, and a teleporter back.
the teleporter also will only move around the player the first time
